service: helpwise-integration

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1
  environment:
    SUPABASE_DATABASE_URL: ${env:SUPABASE_DATABASE_URL}
    SUPABASE_SERVICE_API_KEY: ${env:SUPABASE_SERVICE_API_KEY}
    HELPWISE_KEY: ${env:HELPWISE_KEY}
    HELPWISE_SECRET: ${env:HELPWISE_SECRET}
    BACKENDLESS_APP_ID: ${env:BACKENDLESS_APP_ID}
    BACKENDLESS_SECRET_KEY: ${env:BACKENDLESS_SECRET_KEY}
    HELPWISE_CONVERSATION_TABLE: ${env:HELPWISE_CONVERSATION_TABLE}
    HELPWISE_EMAIL_ACCOUNT: ${env:HELPWISE_EMAIL_ACCOUNT}
    HELP_WHATSAPP_MAILBOX_ID: ${env:HELP_WHATSAPP_MAILBOX_ID}
functions:
  sendMessageToClients:
    handler: handler.sendMessageToClients
    events:
      - http:
          path: /sendmessages
          method: POST
          cors: true
  clientConversations:
    handler: handler.clientConversations
    events:
      - http:
          path: /conversations
          method: GET
  helpWiseHandler:
    handler: handler.helpWiseHandler
    events:
      - http:
          path: /helpwise
          method: POST
          request:
            parameters:
              querystrings:
                action: true
plugins:
  - serverless-offline
